language: objective-c
osx_image: xcode9
install:
- gem install xcpretty
script:
  - set -o pipefail && travis_retry xcodebuild -project KRActivityIndicatorView.xcodeproj -scheme KRActivityIndicatorView -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' test | xcpretty
notifications:
  email: false
